export const createOrderDto = ({
  id = '',
  customerId = '',
  vendorId = '',
  storeId = '',
  items = [],
  subtotal = 0,
  discount = 0,
  deliveryFee = 0,
  total = 0,
  paymentStatus = 'escrow_held',
  deliveryStatus = 'processing',
  otpCode = '',
  deliveryAddress = {},
  createdAt = new Date().toISOString(),
} = {}) => ({
  id,
  customerId,
  vendorId,
  storeId,
  items,
  subtotal,
  discount,
  deliveryFee,
  total,
  paymentStatus,
  deliveryStatus,
  otpCode,
  deliveryAddress,
  createdAt,
})

